FE refactored to work with Rust datatypes
TamahauBrown/poker-trainer pull request #11
Opened 2022-09-17 22:50 UTC by TamahauBrown

2022-09-18 13:11 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
> +            let cards: EquityResponse = {
Instead of creating a new variable with the type, we can just tell typescript that the response from the backend is `EquityResponse`. To do this, put brackets around `res` like so:

```
results.then((res: EquityResponse) => {
...
res.equity = res.equity * 100; // If you still want equity to be a percentage instead of between 0 to 1. I personally think it should be converted later, but that's a personal preference
});
```

2022-09-18 13:11 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
>          let result = invoke('equity_estimate', {});
nit: Move "equity_estimate" to a constant at the topish area of the file. (same place u have `const svg = ...`)

2022-09-18 13:11 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
> +    function hands(cards) {
nit: rename this to `display_hands` to be clearer on it's function

2022-09-18 13:11 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
> +        player_cards(cards.player_hand);
Nice job extracting stuff into different functions and keeping it organized :D

2022-09-18 13:11 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
> +        entries.forEach(function (hand) {
No changes needed, but just to let you know you can also do for each loops like so:
```

2022-09-18 13:52 UTC, 8176135 requested changes
Overall code looks good, the logic makes sense, and most importantly it works :)

2022-09-18 13:52 UTC, 8176135 commented on src/PokerModels/BEVars.ts
> +    Create an object type called Equity Response which transforms the data from equity estimate into a typescript
nit/technicality: There is no transformation taking place. An interface is just telling the typescript engine this is what it is, so that it can assist us when we are typing out code, No data is being changed or moved around when running.

2022-09-18 13:52 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
>      let full_path;
No need for full_path to be a global variable, just define it (with `let`) when you use it.

2022-09-18 13:52 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
> +    function player_cards(entries) {
We can define all function parameters with a type, this way the caller of the function know exactly what to pass in without extra documentation, and is enforced by the compiler. 

For example here entries can be typed: `entries: Hand`. (the Hand type is from the PR comment in BEVars file)

2022-09-18 13:52 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
> +    function board_cards(entries) {
Similarly here, add typing of the type you expect to receive. (An array of cards)

2022-09-18 13:52 UTC, 8176135 commented on src/Components/ExerciseHeader.tsx
> +    function hands(cards) {
> We can define all function parameters with a type, this way the caller of the function know exactly what to pass in without extra documentation, and is enforced by the compiler.

So for this we can define cards like so: `function hands(cards: EquityResponse)`

2022-09-18 13:52 UTC, 8176135 commented on src/PokerModels/BEVars.ts
> +    opponent_hands: [string, unknown][];
Once all the typing is in place, it not only helps with enforcing types, it makes changes/refactoring a lot easier. For example, we discussed in our call about the BE updating the response so that it returns the card names, so you don't have to string it together manually. To update the frontend with that change, the "manual" part will only be to change:
```
export interface Card {
...
```

to 
```
export type Card = string
```

Then the compiler will complain about all the places you need to update, so no worries about missing something when updating.

2022-09-18 23:46 UTC, TamahauBrown commented on src/Components/ExerciseHeader.tsx
> +            let cards: EquityResponse = {
This holds for when we want to declare this locally but the issue lies in the equity calculations actually occur in the ChancesSlider.tsx file. Currently we have no method for BE calculations so this is the only way for the global instanced variable to be exported to that file from the equity estimate function. Check images below for the references to this.
![image](https://user-images.githubusercontent.com/48704237/190933214-ed1a3bdb-30e8-4400-afe0-78e3af368228.png)
![image](https://user-images.githubusercontent.com/48704237/190933216-e5a03134-3ff4-4df5-864f-d2750e3875bd.png)
![image](https://user-images.githubusercontent.com/48704237/190933221-f14a802b-89f6-444e-a288-17606b3eacfc.png)

Once the equity BE calculation is implemented I am happy to refactor the FE to this

2022-09-18 23:49 UTC, TamahauBrown commented on src/Components/ExerciseHeader.tsx
>      let full_path;
https://github.com/TamahauBrown/poker-trainer/pull/11#discussion_r973717600
This relates to my comment here.

2022-09-18 23:50 UTC, TamahauBrown commented on src/Components/ExerciseHeader.tsx
> +    function player_cards(entries) {
I was not worrying about type specific til things were sorted out cleanly but I can do so if need be

2022-09-19 02:41 UTC, TamahauBrown commented on src/Components/ExerciseHeader.tsx
> +        entries.forEach(function (hand) {
Again Python taught me that lol

2022-09-24 07:08 UTC, merged