Bugfixes, minor refactors, and "Lucky" opponent cards
TamahauBrown/poker-trainer pull request #19
Opened 2022-09-30 07:10 UTC by 8176135

- Fixed bug that equity response was always returning 0
- Equity returned is now between 0 - 100, not 0.0 - 1.0
- Equity expected is also between 0 - 100, not 0.0 - 1.0
- For Exercise 1, opponent cards are now more likely to have a higher chance of winning compared to your hand.
  - Opponent essentially is dealt ~45 random hands and the highest win chance is picked from those
- Minor refactors and typing for frontend.

2022-09-30 07:38 UTC, TamahauBrown commented
Test case: 
Chances 3 with slider with incorrect result. Returned incorrect result with "correct" on a 10% difference.
Need explanation on what the acceptance threshold is. Personally I think it should be +- 3%
**Result: Fail**
![image](https://user-images.githubusercontent.com/48704237/193217024-8d6d24a4-c125-4234-b600-c34d3ea53d11.png)

2022-09-30 07:39 UTC, TamahauBrown requested changes
Fix threshold on main exercise

2022-09-30 07:46 UTC, 8176135 commented
Changed definition of success to +/- 3%

2022-09-30 07:46 UTC, TamahauBrown commented
![image](https://user-images.githubusercontent.com/48704237/193218921-8dadc78a-da58-4be9-a5bd-f6a0da32418b.png)
This was before the commit just now but this occurred.

2022-09-30 07:56 UTC, 8176135 commented
I think this is because it's checking against the non rounded value, but displaying a rounded value. It is a bit confusing though, maybe we should display 2dp or something to clarify this.

2022-10-01 07:29 UTC, TamahauBrown commented
# Test cases:
Equity: 24.43%

## 1. 20%
Expected: Incorrect
Result: Incorrect
**Passed**

## 2. 21%
Expected: Correct
Result: Correct
**Passed**

## 3. 27%
Expected: Correct
Result: Correct
**Passed**

## 4. 28%
Expected: Incorrect
Result: Incorrect
**Passed**

Overall result: LGTM, feel free to push it up

2022-10-01 07:30 UTC, TamahauBrown approved these changes
LGTM

2022-10-01 19:20 UTC, merged